### ISSUE TITLE
Runtime error re: IResponseNegotiator.Handle

### ISSUE THREAD

**Issue by ethankershaw** [CarterCommunity/Carter.SirenNegotiator#11]
The signature of Carter's IResponseNegotiator.Handle method has changed to have a generic type parameter on the model. This results in a runtime error:

```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Method 'Handle' in type 'Carter.SirenNegotiator.SirenResponseNegotiator' from assembly 'Carter.SirenNegotiator, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by ethankershaw** [comment]
I think I have this resolved here: [ethankershaw/fix-11](https://github.com/ethankershaw/Carter.SirenNegotiator/tree/ethankershaw/fix-11)

**Comment by jchannon** [comment]
That fix looks good, feel free to send a PR and we'll see if we can get a nuget release out

**Comment by ethankershaw** [comment]
Opened PR #12
